### ISSUE TITLE
Failing to Register Gurobi License on Windows System with Path Which Includes Spaces

### ISSUE THREAD

**Issue by RoyiAvital** [cvxr/CVX#13]
Hello,
I tried registering academic license of Gurobi.
I had failed messages on `cvx_grbgetkey()` function.

On the latest version at the moment (`Version 2.2, January 2020, Build 1148`) there is at line 299 the following:

```matlab
[status,result]=system( sprintf( '%s --path=%s %s', gname, tdir, kcode ) ); %#ok
```

The issue is in case the path of `gname` or `tdir` includes spaces the operation fails.
In order to support spaces the string should have `"` at the beginning and the end.

So something like the following will fix it:

```matlab
gname = ['"', gname, '"'];
tdir= ['"', tdir, '"'];
```

**Comment by mcg1969** [comment]
Closing this in favor of the open-sourced Gurobi shim to come (which will need fixing anyway!)

**Comment by RoyiAvital** [comment]
I am excited to see new updates are coming.
Thanks!
