### ISSUE TITLE
Ill-formed configuration of .gitmodules, from open source point of view

### ISSUE THREAD

**Issue by SeSodesa** [cvxr/CVX#15]
Hello there.

The URLs in the file `.gitmodules` should probably be changed to use the HTTPS protocol instead of SSH, as currently if someone clones via HTTPS, they are prevented from recursively downloading the submodules or dependencies of this project, which I assume are needed for it to function properly.

This would of a simple change of the file `.gitmodules` from

    [submodule "sedumi"]
            path = sedumi
            url = git@github.com:sqlp/sedumi.git
            branch = pretransfo
    [submodule "sdpt3"]
            path = sdpt3
            url = git@github.com:sqlp/sdpt3.git

to

    [submodule "sedumi"]
            path = sedumi
            url = https://github.com/sqlp/sedumi.git
            branch = pretransfo
    [submodule "sdpt3"]
            path = sdpt3
            url = https://github.com/sqlp/sdpt3.git

Not sure how "open source" this project is intended to be, but it is my experience that HTTPS addresses are preferred over git-prefixed ones precisely because of this issue. This way around, if you have SSH-access to the repo, you are still allowed to download the dependencies recursively, while simultaneously not hindering the lives of HTTPS users, who simply intend to fetch updates without ever pushing anything to the repository.

You could also use relative URLs ([link to instructions][rel-url]), but if the submodule repositories are to stay open on GitHub, I am not entirely convinced whether that is necessary.

[rel-url]: https://stackoverflow.com/a/44630028

**Comment by mcg1969** [comment]
We are going to move away from submodules in favor of direct downloads of the compiled bundles of these solvers.
