### ISSUE TITLE
"Could not find a MOSEK MEX file" for release 2.2.2

### ISSUE THREAD

**Issue by Zhaoruiwang** [cvxr/CVX#25]
I have downloaded release 2.2.2 and ran the cvx_setup, and it says "Mosek unknown"  "Could not find a MOSEK MEX file."

**Comment by mcg1969** [comment]
You need to follow MOSEK's instructions for setting up MOSEK in MATLAB. If MATLAB doesn't see Mosek _before_ you run the setup script, CVX won't be able to, either.

**Comment by mcg1969** [comment]
Closing, but if you can demonstrate that mosek is on your MATLAB path before you run cvx_setup, please provide a copy of the MATLAB output showing the issue.
