### ISSUE TITLE
Sedumi Submodule init doesn't work

### ISSUE THREAD

**Issue by imciner2** [cvxr/CVX#3]
Doing a "git submodule init" on a freshly cloned version of this repository is giving the error:
Fetched in submodule path 'sedumi', but it did not contain 360a29fd60d84fc4973357df0b566e93a1272624. Direct fetching of that commit failed."

**Comment by mcg1969** [comment]
We are removing submodule support in favor of a direct download of the relevant solver bundles, due to our ability to build MEX files for all of them in CI now.
